module.export = {
    content: [
      "src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "semantic-bg-primary": "var(--semantic-bg-primary)",
"semantic-bg-alt-primary": "var(--semantic-bg-alt-primary)",
"semantic-bg-base-bg": "var(--semantic-bg-base-bg)",
"semantic-bg-secondary": "var(--semantic-bg-secondary)",
"semantic-bg-line": "var(--semantic-bg-line)",
"semantic-bg-secondary-primary": "var(--semantic-bg-secondary-primary)",
"semantic-bg-secondary-alt-primary": "var(--semantic-bg-secondary-alt-primary)",
"semantic-bg-secondary-secondary": "var(--semantic-bg-secondary-secondary)",
"semantic-bg-secondary-base-bg": "var(--semantic-bg-secondary-base-bg)",
"semantic-bg-secondary-line": "var(--semantic-bg-secondary-line)",
"semantic-fg-primary": "var(--semantic-fg-primary)",
"semantic-fg-secondary": "var(--semantic-fg-secondary)",
"semantic-fg-disabled": "var(--semantic-fg-disabled)",
"semantic-fg-on-default": "var(--semantic-fg-on-default)",
"semantic-fg-primary-on-bg-secondary": "var(--semantic-fg-primary-on-bg-secondary)",
"semantic-fg-secondary-on-bg-secondary": "var(--semantic-fg-secondary-on-bg-secondary)",
"semantic-fg-disabled-on-secondary-bg": "var(--semantic-fg-disabled-on-secondary-bg)",
"semantic-accent-bg": "var(--semantic-accent-bg)",
"semantic-accent-default": "var(--semantic-accent-default)",
"semantic-accent-hover": "var(--semantic-accent-hover)",
"semantic-accent-pressed": "var(--semantic-accent-pressed)",
"semantic-accent-on-bg": "var(--semantic-accent-on-bg)",
"semantic-warning-bg": "var(--semantic-warning-bg)",
"semantic-warning-default": "var(--semantic-warning-default)",
"semantic-warning-hover": "var(--semantic-warning-hover)",
"semantic-warning-pressed": "var(--semantic-warning-pressed)",
"semantic-warning-on-bg": "var(--semantic-warning-on-bg)",
"semantic-error-bg": "var(--semantic-error-bg)",
"semantic-error-default": "var(--semantic-error-default)",
"semantic-error-hover": "var(--semantic-error-hover)",
"semantic-error-pressed": "var(--semantic-error-pressed)",
"semantic-error-on-bg": "var(--semantic-error-on-bg)",
"semantic-success-bg": "var(--semantic-success-bg)",
"semantic-success-default": "var(--semantic-success-default)",
"semantic-success-hover": "var(--semantic-success-hover)",
"semantic-success-pressed": "var(--semantic-success-pressed)",
"semantic-success-on-bg": "var(--semantic-success-on-bg)",
"semantic-info-bg": "var(--semantic-info-bg)",
"semantic-info-icon-on-bg": "var(--semantic-info-icon-on-bg)",
"semantic-info-primary-text-on-bg": "var(--semantic-info-primary-text-on-bg)",
"semantic-info-secondary-text-on-bg": "var(--semantic-info-secondary-text-on-bg)"
        },
        boxShadow: {
          "xxs": "var(--shadow-xxs-shadow)",
"xs": "var(--shadow-xs-shadow)",
"sm": "var(--shadow-sm-shadow)",
"md": "var(--shadow-md-shadow)",
"lg": "var(--shadow-lg-shadow)",
"xl": "var(--shadow-xl-shadow)",
"xxl": "var(--shadow-xxl-shadow)"
        },
        borderWidth: {"none": "0px",
"xxs": "0.5px",
"xs": "1px",
"sm": "1.5px",
"md": "2px",
"lg": "2.5px",
"xl": "3px",
"xxl": "4px"},
        opacity: {"0": "0%",
"5": "5%",
"10": "10%",
"15": "15%",
"20": "20%",
"25": "25%",
"30": "30%",
"35": "35%",
"40": "40%",
"45": "45%",
"50": "50%",
"55": "55%",
"60": "60%",
"65": "65%",
"70": "70%",
"75": "75%",
"80": "80%",
"85": "85%",
"90": "90%",
"95": "95%",
"100": "100%"},
        spacing: {"none": "0px",
"1": "4px",
"2": "8px",
"3": "12px",
"4": "16px",
"5": "20px",
"6": "24px",
"7": "32px",
"8": "40px",
"9": "48px",
"10": "56px",
"11": "64px",
"12": "72px",
"13": "80px",
"14": "88px",
"15": "96px",
"16": "112px",
"17": "128px",
"18": "160px",
"19": "192px",
"20": "224px",
"21": "256px"},
        borderRadius: {"none": "0px",
"xxs": "4px",
"xs": "6px",
"s": "8px",
"m": "16px",
"l": "24px",
"xl": "32px",
"xxl": "64px",
"pill": "200px"}
      },
    },
    plugins: [
      ({ addUtilities }) => {
        addUtilities({".product-headings-heading-1": {"fontFamily":"IBM Plex Sans","fontWeight":"Bold","lineHeight":"32","fontSize":"28","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-headings-heading-2": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"28","fontSize":"22","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-headings-heading-3": {"fontFamily":"IBM Plex Sans","fontWeight":"Bold","lineHeight":"24","fontSize":"20","letterSpacing":"0","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-headings-heading-4": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"24","fontSize":"18","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-headings-heading-5": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"20","fontSize":"16","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-headings-heading-6": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"16","fontSize":"14","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-1-regular": {"fontFamily":"IBM Plex Sans","fontWeight":"Regular","lineHeight":"28","fontSize":"18","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-1-medium": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"28","fontSize":"18","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-1-italic": {"fontFamily":"IBM Plex Sans","fontWeight":"Italic","lineHeight":"28","fontSize":"18","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-1-semibold": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"28","fontSize":"18","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-2-regular": {"fontFamily":"IBM Plex Sans","fontWeight":"Regular","lineHeight":"24","fontSize":"16","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-2-medium": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"24","fontSize":"16","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-2-italic": {"fontFamily":"IBM Plex Sans","fontWeight":"Italic","lineHeight":"24","fontSize":"16","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-2-semibold": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"24","fontSize":"16","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-3-regular": {"fontFamily":"IBM Plex Sans","fontWeight":"Regular","lineHeight":"20","fontSize":"14","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-3-medium": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"20","fontSize":"14","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-3-italic": {"fontFamily":"IBM Plex Sans","fontWeight":"Italic","lineHeight":"20","fontSize":"14","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-3-semibold": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"20","fontSize":"14","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-4-regular": {"fontFamily":"IBM Plex Sans","fontWeight":"Regular","lineHeight":"16","fontSize":"12","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-4-medium": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"16","fontSize":"12","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-4-italic": {"fontFamily":"IBM Plex Sans","fontWeight":"Italic","lineHeight":"16","fontSize":"12","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-body-text-4-semibold": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"16","fontSize":"12","letterSpacing":"0%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"none","textDecoration":"none"},
".product-label-label-1": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"12","fontSize":"12","letterSpacing":"0.65","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"uppercase","textDecoration":"none"},
".product-label-label-2": {"fontFamily":"IBM Plex Sans","fontWeight":"Medium","lineHeight":"10","fontSize":"10","letterSpacing":"0.5","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"uppercase","textDecoration":"none"},
".product-button-button-1": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"16","fontSize":"16","letterSpacing":"2%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"capitalize","textDecoration":"none"},
".product-button-button-2": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"14","fontSize":"14","letterSpacing":"2%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"capitalize","textDecoration":"none"},
".product-button-button-3": {"fontFamily":"IBM Plex Sans","fontWeight":"SemiBold","lineHeight":"12","fontSize":"12","letterSpacing":"2%","paragraphSpacing":"0","paragraphIndent":"0px","textCase":"capitalize","textDecoration":"none"}})
      },
    ],
  }