import { Pipeline } from "./types";

export const mockPipeline: Pipeline = {
  name: "pipelines/p02",
  uid: "6da71613-cb95-45f0-ac88-a9fcec5a3dc2",
  id: "p02",
  description: "string",
  mode: "MODE_SYNC",
  state: "STATE_ACTIVE",
  user: "users/d7dca98d-544d-4f56-ba98-720371d99bfe",
  create_time: "2023-05-16T06:35:31.711163Z",
  update_time: "2023-05-16T06:35:31.711163Z",
  recipe: {
    version: "v1alpha",
    components: [
      {
        id: "s01",
        resource_name: "source-connectors/source-http",
        resource_detail: {
          connector: {
            create_time: "2023-05-16T05:56:45.551790Z",
            description: "",
            state: "STATE_CONNECTED",
            update_time: "2023-05-16T05:56:45.555522Z",
            user: "users/d7dca98d-544d-4f56-ba98-720371d99bfe",
          },
          id: "source-http",
          name: "source-connectors/source-http",
          source_connector_definition:
            "source-connector-definitions/source-http",
          source_connector_definition_detail: {
            connector_definition: {
              create_time: "2023-05-16T02:43:06.336673Z",
              docker_repository: "instill-ai/source-http",
              documentation_url:
                "https://www.instill.tech/docs/source-connectors/http",
              icon: "http.svg",
              public: true,
              release_date: {},
              release_stage: "RELEASE_STAGE_GENERALLY_AVAILABLE",
              resource_requirements: {},
              title: "HTTP",
              update_time: "2023-05-16T02:43:06.336673Z",
            },
            id: "source-http",
            name: "source-connector-definitions/source-http",
            uid: "f20a3c02-c70e-4e76-8566-7c13ca11d18d",
          },
          uid: "a4d59ae6-51dc-4c64-bd39-f86e86521e54",
        },
        metadata: null,
        dependencies: {},
      },
      {
        id: "m01",
        resource_name: "models/m01",
        resource_detail: {
          create_time: "2023-05-16T06:11:12.131611Z",
          description: "",
          id: "m01",
          model_definition: "model-definitions/github",
          model_definition_detail: {
            create_time: "2023-05-16T02:43:06.730195Z",
            documentation_url:
              "https://www.instill.tech/docs/import-models/github",
            icon: "github.svg",
            id: "github",
            model_spec: {
              $schema: "http://json-schema.org/draft-07/schema#",
              additional_properties: false,
              maxProperties: 3,
              minProperties: 2,
              properties: {
                html_url: {
                  description:
                    "The URL of the GitHub repository, e.g. `https://github.com/instill-ai/model-yolov7`.",
                  examples: [
                    "https://github.com/instill-ai/model-yolov7",
                    "https://github.com/instill-ai/model-mobilenetv2",
                  ],
                  maxLength: 1023,
                  minLength: 0,
                  read_only: true,
                  title: "Github repository URL",
                  type: "string",
                  ui_component: "text",
                  ui_disabled: true,
                  ui_hidden: true,
                  ui_order: 2,
                },
                repository: {
                  description:
                    "The name of a public GitHub repository, e.g. `instill-ai/model-yolov7`.",
                  examples: [
                    "instill-ai/model-yolov7",
                    "instill-ai/model-mobilenetv2",
                  ],
                  maxLength: 1023,
                  minLength: 0,
                  title: "GitHub repository",
                  type: "string",
                  ui_component: "text",
                  ui_order: 0,
                },
                tag: {
                  description:
                    "The tag of the GitHub repository, e.g., `v0.1.0`.",
                  examples: ["v0.1.0-alpha", "v1.0.0"],
                  maxLength: 200,
                  minLength: 0,
                  read_only: true,
                  title: "GitHub repository tag",
                  type: "string",
                  ui_component: "text",
                  ui_disabled: true,
                  ui_order: 1,
                },
              },
              required: ["repository", "tag"],
              title: "GitHub spec for model",
              type: "object",
            },
            name: "model-definitions/github",
            release_stage: "RELEASE_STAGE_ALPHA",
            title: "GitHub",
            uid: "909c3278-f7d1-461c-9352-87741bef11d3",
            update_time: "2023-05-16T02:43:06.730195Z",
          },
          name: "models/m01",
          state: "STATE_ONLINE",
          task: "TASK_CLASSIFICATION",
          uid: "b403ccf2-7fa8-4aa7-b7d2-cf6c5135e38b",
          update_time: "2023-05-16T06:11:13.194361Z",
          user: "users/d7dca98d-544d-4f56-ba98-720371d99bfe",
          visibility: "VISIBILITY_PUBLIC",
        },
        metadata: null,
        dependencies: {},
      },
      {
        id: "m02",
        resource_name: "models/m01",
        resource_detail: {
          create_time: "2023-05-16T06:11:12.131611Z",
          description: "",
          id: "m01",
          model_definition: "model-definitions/github",
          model_definition_detail: {
            create_time: "2023-05-16T02:43:06.730195Z",
            documentation_url:
              "https://www.instill.tech/docs/import-models/github",
            icon: "github.svg",
            id: "github",
            model_spec: {
              $schema: "http://json-schema.org/draft-07/schema#",
              additional_properties: false,
              maxProperties: 3,
              minProperties: 2,
              properties: {
                html_url: {
                  description:
                    "The URL of the GitHub repository, e.g. `https://github.com/instill-ai/model-yolov7`.",
                  examples: [
                    "https://github.com/instill-ai/model-yolov7",
                    "https://github.com/instill-ai/model-mobilenetv2",
                  ],
                  maxLength: 1023,
                  minLength: 0,
                  read_only: true,
                  title: "Github repository URL",
                  type: "string",
                  ui_component: "text",
                  ui_disabled: true,
                  ui_hidden: true,
                  ui_order: 2,
                },
                repository: {
                  description:
                    "The name of a public GitHub repository, e.g. `instill-ai/model-yolov7`.",
                  examples: [
                    "instill-ai/model-yolov7",
                    "instill-ai/model-mobilenetv2",
                  ],
                  maxLength: 1023,
                  minLength: 0,
                  title: "GitHub repository",
                  type: "string",
                  ui_component: "text",
                  ui_order: 0,
                },
                tag: {
                  description:
                    "The tag of the GitHub repository, e.g., `v0.1.0`.",
                  examples: ["v0.1.0-alpha", "v1.0.0"],
                  maxLength: 200,
                  minLength: 0,
                  read_only: true,
                  title: "GitHub repository tag",
                  type: "string",
                  ui_component: "text",
                  ui_disabled: true,
                  ui_order: 1,
                },
              },
              required: ["repository", "tag"],
              title: "GitHub spec for model",
              type: "object",
            },
            name: "model-definitions/github",
            release_stage: "RELEASE_STAGE_ALPHA",
            title: "GitHub",
            uid: "909c3278-f7d1-461c-9352-87741bef11d3",
            update_time: "2023-05-16T02:43:06.730195Z",
          },
          name: "models/m01",
          state: "STATE_ONLINE",
          task: "TASK_CLASSIFICATION",
          uid: "b403ccf2-7fa8-4aa7-b7d2-cf6c5135e38b",
          update_time: "2023-05-16T06:11:13.194361Z",
          user: "users/d7dca98d-544d-4f56-ba98-720371d99bfe",
          visibility: "VISIBILITY_PUBLIC",
        },
        metadata: null,
        dependencies: {},
      },
      {
        id: "d01",
        resource_name: "destination-connectors/destination-http",
        resource_detail: {
          connector: {
            create_time: "2023-05-16T05:56:50.968236Z",
            description: "",
            state: "STATE_CONNECTED",
            update_time: "2023-05-16T05:56:50.972884Z",
            user: "users/d7dca98d-544d-4f56-ba98-720371d99bfe",
          },
          destination_connector_definition:
            "destination-connector-definitions/destination-http",
          destination_connector_definition_detail: {
            connector_definition: {
              create_time: "2023-05-16T02:43:06.342962Z",
              docker_repository: "instill-ai/destination-http",
              documentation_url:
                "https://www.instill.tech/docs/destination-connectors/http",
              icon: "http.svg",
              public: true,
              release_date: {},
              release_stage: "RELEASE_STAGE_GENERALLY_AVAILABLE",
              resource_requirements: {},
              title: "HTTP",
              update_time: "2023-05-16T02:43:06.342962Z",
            },
            id: "destination-http",
            name: "destination-connector-definitions/destination-http",
            uid: "909c3278-f7d1-461c-9352-87741bef11d3",
          },
          id: "destination-http",
          name: "destination-connectors/destination-http",
          uid: "3a84753b-8388-4fa3-ae7b-a5dd0d84c71d",
        },
        metadata: null,
        dependencies: {},
      },
    ],
  },
};
