name: cd-deploy-to-staging-storybook

on:
  pull_request:
    branches:
      - "staging"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Cache build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore build cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Lint
        run: yarn lint

  testUnit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore build cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Run unit test
        run: yarn test:coverage

  deployToStorybook:
    if: ${{ !contains(github.ref, 'release') }}
    runs-on: ubuntu-latest
    needs: [lint, testUnit]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.BOTTOKEN }}
          env: preview

      - name: Deploy storybook to vercel
        id: deployStorybookToVercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCELTOKEN }}
          github-token: ${{ secrets.BOTTOKEN }}
          vercel-org-id: ${{ secrets.VERCELORGID }}
          vercel-project-id: ${{ secrets.DESIGNSYSTEMSTORYBOOKID}}
          scope: ${{ secrets.VERCELORGID }}
          github-comment: true
          alias-domains: |
            ui.instill-inc.tech

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
